[package]
authors = ["Solana Labs Maintainers <maintainers@solanalabs.com>"]
description = "SPL-Stake-Pool Command-line Utility"
edition = "2021"
homepage = "https://spl.solana.com/stake-pool"
license = "Apache-2.0"
name = "spl-stake-pool-cli"
repository = "https://github.com/solana-labs/solana-program-library"
version = "1.0.0"

[dependencies]
borsh = "1.2.1"
clap = "2.33.3"
serde = "1.0.197"
serde_derive = "1.0.130"
serde_json = "1.0.114"
solana-account-decoder = ">=1.18.2,<=2"
solana-clap-utils = ">=1.18.2,<=2"
solana-cli-config = ">=1.18.2,<=2"
solana-cli-output = ">=1.18.2,<=2"
solana-client = ">=1.18.2,<=2"
solana-logger = ">=1.18.2,<=2"
solana-program = ">=1.18.2,<=2"
solana-remote-wallet = ">=1.18.2,<=2"
solana-sdk = ">=1.18.2,<=2"
spl-associated-token-account = { version = "=2.3", path = "../../associated-token-account/program", features = [
  "no-entrypoint",
] }
spl-stake-pool = { version = "=1.0.0", path = "../program", features = [
  "no-entrypoint",
] }
spl-token = { version = "=4.0", path = "../../token/program", features = [
  "no-entrypoint",
] }
bs58 = "0.4.0"
bincode = "1.3.1"

[[bin]]
name = "spl-stake-pool"
path = "src/main.rs"
